<a href="https://colab.research.google.com/github/Katiaaaa/Neural-Networks/blob/main/Lab2/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Лабораторна робота №2

### студентки групи КН-31 Валько Катерини

## TensorFlow
За матеріалами ознайомитись із засадами бібліотеки TensorFlow:
- засвоєння поняття тензору
- знати різні способи створення тензорів
- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)
- продемонструвати основні математичні операції над тензорами
- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)


### Поняття тензору, різні способи створення тензорів
Тензори - це об'єкти, які описують лінійне відношення між векторами, скалярами та іншими тензорами. Тензори - багатовимірні масиви.

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [10]:
tensor = tf.Variable([[3, 3, 13, 14],[2, 2, 12, 13]])
print(tensor)

print(tf.constant([[7, 1, 1],
                   [8, 2, 10]]))

print(tf.random.Generator.from_seed(123).normal(shape=(2,3)))


<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 3,  3, 13, 14],
       [ 2,  2, 12, 13]], dtype=int32)>
tf.Tensor(
[[ 7  1  1]
 [ 8  2 10]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 0.8673864  -0.29899067 -0.9310337 ]
 [-1.5828488   1.2481191  -0.6770643 ]], shape=(2, 3), dtype=float32)


### Cтворити набір даних із заданим розподілом, визначити його властивості (shape, rank, size, axis)

In [11]:
tensor = tf.Variable([
                   [1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10]
                   ])

print(tensor.shape)
print(tf.rank(tensor))
print(tf.size(tensor))
#розширення форми масиву. Нова вісь, яка з’явиться в позиції осі у формі розгорнутого масиву.
print(tf.expand_dims(tensor, axis=0))



(2, 5)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]], shape=(1, 2, 5), dtype=int32)


### Продемонструвати основні математичні операції над тензорами

In [29]:
tensor = tf.Variable([
                   [3, 3, 13, 14],
                   [2, 2, 1, 13],
                   [5, 6, 12, 5],
                   [4, 7, 0, 15]])

print(tensor+10)
print(tensor*10)
print(tensor@tf.reshape(tensor, shape=(4, 4)))

tf.Tensor(
[[13 13 23 24]
 [12 12 11 23]
 [15 16 22 15]
 [14 17 10 25]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 30  30 130 140]
 [ 20  20  10 130]
 [ 50  60 120  50]
 [ 40  70   0 150]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[136 191 198 356]
 [ 67 107  40 254]
 [107 134 215 283]
 [ 86 131  59 372]], shape=(4, 4), dtype=int32)


### Провести CRUD операції над даними (reshape, інтеграцію з np.array, pd.DataFrame)

In [31]:
tensor = tf.Variable([
                   [3, 3, 13, 14],
                   [2, 2, 1, 13],
                   [5, 6, 12, 5],
                   [4, 7, 0, 15]])

# CRUD операції над даними, reshape, інтеграція з np.array, pd.DataFrame
tf.compat.v1.assign(tensor[2], [4, 7, 0, 15])
print(tf.slice(tensor, [1, 0], [1, 4]))
print(tf.reshape(tensor, shape=(2, 8)))
print(tf.Variable(np.array([[1, 4], [2, 9]])))
print(tf.Variable(pd.DataFrame([[1, 4], [2, 9]])))

tf.Tensor([[ 2  2  1 13]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[ 3  3 13 14  2  2  1 13]
 [ 4  7  0 15  4  7  0 15]], shape=(2, 8), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 4],
       [2, 9]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 4],
       [2, 9]])>


#Висновок
На лабораторній роботі ми розглянули основи бібліотеки TensorFlow, 
засвоїли поняття тензору, описали різні способи створення тензорів, створили набір даних із заданим розподілом і визначили його властивості (shape, rank, size, axis), продемонстрували основні математичні операції над тензорами, провели CRUD операції над даними (reshape, інтеграцію з np.array, pd.DataFrame)
навчились застосовувати отримані знання на практиці.
 